services:
  datapusher:
    container_name: datapusher
    image: ghcr.io/keitaroinc/datapusher:${DATAPUSHER_VERSION}
    networks:
      - frontend
      - backend
    ports:
      - "8000:8000"
    env_file:
      - ${PWD}/config/backend-services/.datapusher-env

  db:
    container_name: db
    build:
      context: ${PWD}/postgresql
    networks:
      - backend
    env_file:
      - ${PWD}/config/backend-services/.postgres-env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    container_name: solr
    build:
      context: ${PWD}/solr
      args:
        CKAN_BRANCH: ckan-${CKAN_VERSION}
        SOLR_VERSION: ${SOLR_VERSION}
    networks:
      - backend
    env_file:
      - ${PWD}/config/.global-env
      - ${PWD}/config/backend-services/.solr-env
    volumes:
      - solr_data:/var/solr
    healthcheck:
      test: ["CMD-SHELL", "/opt/solr/bin/solr","status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pg_data:
  solr_data:
