# docker-compose build && docker-compose up -d
include:
  - path: config/ckan/ckan.yaml
    env_file: 
      - config/ckan/.env
      - config/.global-env
    project_directory: .
  - path: config/backend-services/backend-services.yaml
    env_file: 
      - config/backend-services/.postgres-env
      - config/.global-env
    project_directory: .

networks:
  frontend:
  backend:
